// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserStatus int32

const (
	UserStatus_invited UserStatus = 0
	UserStatus_created UserStatus = 1
	UserStatus_merged  UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "invited",
	1: "created",
	2: "merged",
}
var UserStatus_value = map[string]int32{
	"invited": 0,
	"created": 1,
	"merged":  2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}
func (UserStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type User struct {
	Id         string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email      string                      `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	CreatedAt  *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt  *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Verified   bool                        `protobuf:"varint,5,opt,name=verified" json:"verified,omitempty"`
	AuthToken  string                      `protobuf:"bytes,6,opt,name=authToken" json:"authToken,omitempty"`
	Status     UserStatus                  `protobuf:"varint,7,opt,name=status,enum=protobuf.UserStatus" json:"status,omitempty"`
	FacebookID string                      `protobuf:"bytes,8,opt,name=facebookID" json:"facebookID,omitempty"`
	UserName   string                      `protobuf:"bytes,9,opt,name=userName" json:"userName,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_invited
}

func (m *User) GetFacebookID() string {
	if m != nil {
		return m.FacebookID
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserPublic struct {
	Id         string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email      string     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Status     UserStatus `protobuf:"varint,3,opt,name=status,enum=protobuf.UserStatus" json:"status,omitempty"`
	FacebookID string     `protobuf:"bytes,4,opt,name=facebookID" json:"facebookID,omitempty"`
	UserName   string     `protobuf:"bytes,5,opt,name=userName" json:"userName,omitempty"`
}

func (m *UserPublic) Reset()                    { *m = UserPublic{} }
func (m *UserPublic) String() string            { return proto.CompactTextString(m) }
func (*UserPublic) ProtoMessage()               {}
func (*UserPublic) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *UserPublic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserPublic) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserPublic) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_invited
}

func (m *UserPublic) GetFacebookID() string {
	if m != nil {
		return m.FacebookID
	}
	return ""
}

func (m *UserPublic) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UsersPublic struct {
	Users []*UserPublic `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UsersPublic) Reset()                    { *m = UsersPublic{} }
func (m *UsersPublic) String() string            { return proto.CompactTextString(m) }
func (*UsersPublic) ProtoMessage()               {}
func (*UsersPublic) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *UsersPublic) GetUsers() []*UserPublic {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserEmailAuth struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *UserEmailAuth) Reset()                    { *m = UserEmailAuth{} }
func (m *UserEmailAuth) String() string            { return proto.CompactTextString(m) }
func (*UserEmailAuth) ProtoMessage()               {}
func (*UserEmailAuth) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *UserEmailAuth) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserEmailAuth) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserEmailAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserFacebookAuth struct {
	FacebookID       string `protobuf:"bytes,1,opt,name=facebookID" json:"facebookID,omitempty"`
	FacebookEmail    string `protobuf:"bytes,2,opt,name=facebookEmail" json:"facebookEmail,omitempty"`
	FacebookUsername string `protobuf:"bytes,3,opt,name=facebookUsername" json:"facebookUsername,omitempty"`
	FacebookToken    string `protobuf:"bytes,4,opt,name=facebookToken" json:"facebookToken,omitempty"`
}

func (m *UserFacebookAuth) Reset()                    { *m = UserFacebookAuth{} }
func (m *UserFacebookAuth) String() string            { return proto.CompactTextString(m) }
func (*UserFacebookAuth) ProtoMessage()               {}
func (*UserFacebookAuth) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *UserFacebookAuth) GetFacebookID() string {
	if m != nil {
		return m.FacebookID
	}
	return ""
}

func (m *UserFacebookAuth) GetFacebookEmail() string {
	if m != nil {
		return m.FacebookEmail
	}
	return ""
}

func (m *UserFacebookAuth) GetFacebookUsername() string {
	if m != nil {
		return m.FacebookUsername
	}
	return ""
}

func (m *UserFacebookAuth) GetFacebookToken() string {
	if m != nil {
		return m.FacebookToken
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*UserPublic)(nil), "protobuf.UserPublic")
	proto.RegisterType((*UsersPublic)(nil), "protobuf.UsersPublic")
	proto.RegisterType((*UserEmailAuth)(nil), "protobuf.UserEmailAuth")
	proto.RegisterType((*UserFacebookAuth)(nil), "protobuf.UserFacebookAuth")
	proto.RegisterEnum("protobuf.UserStatus", UserStatus_name, UserStatus_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6a, 0xdc, 0x30,
	0x10, 0xae, 0xbc, 0xbb, 0x8e, 0x3d, 0x26, 0xc1, 0x88, 0x1c, 0xc4, 0x52, 0x5a, 0x63, 0x7a, 0x30,
	0x4b, 0x71, 0x60, 0x7b, 0x69, 0x8f, 0x81, 0xa6, 0xd0, 0x4b, 0x29, 0x6e, 0x7a, 0xec, 0x41, 0x5e,
	0x69, 0x37, 0x22, 0xeb, 0x95, 0xb1, 0xe4, 0xf4, 0x65, 0xfa, 0x04, 0x7d, 0x8e, 0x3e, 0x58, 0x91,
	0xe4, 0xdf, 0x04, 0xfa, 0x73, 0x32, 0xf3, 0xcd, 0xcc, 0xf7, 0x33, 0x16, 0x40, 0xab, 0x78, 0x93,
	0xd7, 0x8d, 0xd4, 0x12, 0x07, 0xf6, 0x53, 0xb6, 0xfb, 0xf5, 0xcb, 0x83, 0x94, 0x87, 0x23, 0xbf,
	0xea, 0x81, 0x2b, 0x2d, 0x2a, 0xae, 0x34, 0xad, 0x6a, 0x37, 0x9a, 0xfe, 0xf2, 0x60, 0xf9, 0x55,
	0xf1, 0x06, 0x5f, 0x80, 0x27, 0x18, 0x41, 0x09, 0xca, 0xc2, 0xc2, 0x13, 0x0c, 0x5f, 0xc2, 0x8a,
	0x57, 0x54, 0x1c, 0x89, 0x67, 0x21, 0x57, 0xe0, 0xb7, 0x10, 0xee, 0x1a, 0x4e, 0x35, 0x67, 0xd7,
	0x9a, 0x2c, 0x12, 0x94, 0x45, 0xdb, 0x75, 0xee, 0x34, 0xf2, 0x5e, 0x23, 0xbf, 0xed, 0x35, 0x8a,
	0x71, 0xd8, 0x6c, 0xb6, 0x35, 0xeb, 0x36, 0x97, 0x7f, 0xdf, 0x1c, 0x86, 0xf1, 0x1a, 0x82, 0x07,
	0xde, 0x88, 0xbd, 0xe0, 0x8c, 0xac, 0x12, 0x94, 0x05, 0xc5, 0x50, 0xe3, 0xe7, 0x10, 0xd2, 0x56,
	0xdf, 0xdd, 0xca, 0x7b, 0x7e, 0x22, 0xbe, 0x75, 0x3a, 0x02, 0xf8, 0x35, 0xf8, 0x4a, 0x53, 0xdd,
	0x2a, 0x72, 0x96, 0xa0, 0xec, 0x62, 0x7b, 0x39, 0x2a, 0x99, 0xcc, 0x5f, 0x6c, 0xaf, 0xe8, 0x66,
	0xf0, 0x0b, 0x80, 0x3d, 0xdd, 0xf1, 0x52, 0xca, 0xfb, 0x8f, 0xef, 0x49, 0x60, 0xc9, 0x26, 0x88,
	0xf1, 0x61, 0x6e, 0xfc, 0x89, 0x56, 0x9c, 0x84, 0xb6, 0x3b, 0xd4, 0xe9, 0x0f, 0x04, 0x60, 0x28,
	0x3f, 0xb7, 0xe5, 0x51, 0xec, 0xfe, 0xf1, 0x98, 0xa3, 0xbd, 0xc5, 0x7f, 0xdb, 0x5b, 0xfe, 0xd1,
	0xde, 0xea, 0x91, 0xbd, 0x77, 0x10, 0x19, 0x46, 0xd5, 0xd9, 0xdb, 0xc0, 0xca, 0xb4, 0x14, 0x41,
	0xc9, 0x22, 0x8b, 0x1e, 0xeb, 0xba, 0xa1, 0xc2, 0x8d, 0xa4, 0xdf, 0xe0, 0xdc, 0x80, 0x37, 0xc6,
	0xf1, 0x75, 0xab, 0xef, 0xc6, 0x2c, 0x68, 0x9a, 0x65, 0xaa, 0xee, 0xcd, 0xd5, 0x4d, 0xaf, 0xa6,
	0x4a, 0x7d, 0x97, 0x0d, 0xb3, 0x49, 0xc3, 0x62, 0xa8, 0xd3, 0x9f, 0x08, 0x62, 0xc3, 0xff, 0xa1,
	0x0b, 0x62, 0x25, 0xe6, 0x51, 0xd1, 0x93, 0xa8, 0xaf, 0xe0, 0xbc, 0xaf, 0x6e, 0x26, 0x67, 0x9d,
	0x83, 0x78, 0x03, 0x71, 0x0f, 0x18, 0x85, 0x93, 0xb1, 0xe6, 0xe4, 0x9f, 0xe0, 0x53, 0x46, 0xf7,
	0x96, 0x96, 0x73, 0x46, 0x0b, 0x6e, 0xb6, 0xee, 0x27, 0xbb, 0x1f, 0x83, 0x23, 0x38, 0x13, 0xa7,
	0x07, 0xa1, 0x39, 0x8b, 0x9f, 0x99, 0xa2, 0x7b, 0xeb, 0x31, 0xc2, 0x00, 0x7e, 0xc5, 0x9b, 0x03,
	0x67, 0xb1, 0x57, 0xfa, 0xf6, 0xb6, 0x6f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x31, 0xc4, 0xfd,
	0x8f, 0xa0, 0x03, 0x00, 0x00,
}
