// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserStatus int32

const (
	UserStatus_invited UserStatus = 0
	UserStatus_created UserStatus = 1
)

var UserStatus_name = map[int32]string{
	0: "invited",
	1: "created",
}
var UserStatus_value = map[string]int32{
	"invited": 0,
	"created": 1,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}
func (UserStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type User struct {
	Id        string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email     string                      `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Verified  bool                        `protobuf:"varint,5,opt,name=verified" json:"verified,omitempty"`
	AuthToken string                      `protobuf:"bytes,6,opt,name=authToken" json:"authToken,omitempty"`
	Status    UserStatus                  `protobuf:"varint,7,opt,name=status,enum=protobuf.UserStatus" json:"status,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_invited
}

type UserPublic struct {
	Id     string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email  string     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Status UserStatus `protobuf:"varint,3,opt,name=status,enum=protobuf.UserStatus" json:"status,omitempty"`
}

func (m *UserPublic) Reset()                    { *m = UserPublic{} }
func (m *UserPublic) String() string            { return proto.CompactTextString(m) }
func (*UserPublic) ProtoMessage()               {}
func (*UserPublic) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *UserPublic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserPublic) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserPublic) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_invited
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*UserPublic)(nil), "protobuf.UserPublic")
	proto.RegisterEnum("protobuf.UserStatus", UserStatus_name, UserStatus_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x6a, 0xc3, 0x30,
	0x10, 0x84, 0x2b, 0x27, 0x71, 0xec, 0x0d, 0x84, 0x20, 0x72, 0x10, 0xa6, 0x50, 0x93, 0x43, 0x31,
	0xa5, 0x38, 0x90, 0x5e, 0x7a, 0xed, 0x1b, 0x14, 0x37, 0xbd, 0xd7, 0x8e, 0x36, 0xa9, 0xa8, 0x1d,
	0x19, 0xfd, 0xe4, 0x19, 0xfa, 0xd8, 0xc5, 0x92, 0x1d, 0x1f, 0xd3, 0x93, 0x98, 0xd1, 0x8c, 0x3e,
	0xed, 0x02, 0x58, 0x8d, 0x2a, 0x6f, 0x95, 0x34, 0x92, 0x46, 0xee, 0xa8, 0xec, 0x31, 0x79, 0x38,
	0x49, 0x79, 0xaa, 0x71, 0x3b, 0x18, 0x5b, 0x23, 0x1a, 0xd4, 0xa6, 0x6c, 0x5a, 0x1f, 0xdd, 0xfc,
	0x06, 0x30, 0xfd, 0xd4, 0xa8, 0xe8, 0x12, 0x02, 0xc1, 0x19, 0x49, 0x49, 0x16, 0x17, 0x81, 0xe0,
	0x74, 0x0d, 0x33, 0x6c, 0x4a, 0x51, 0xb3, 0xc0, 0x59, 0x5e, 0xd0, 0x57, 0x88, 0x0f, 0x0a, 0x4b,
	0x83, 0xfc, 0xcd, 0xb0, 0x49, 0x4a, 0xb2, 0xc5, 0x2e, 0xc9, 0x3d, 0x23, 0x1f, 0x18, 0xf9, 0x7e,
	0x60, 0x14, 0x63, 0xb8, 0x6b, 0xda, 0x96, 0xf7, 0xcd, 0xe9, 0xed, 0xe6, 0x35, 0x4c, 0x13, 0x88,
	0x2e, 0xa8, 0xc4, 0x51, 0x20, 0x67, 0xb3, 0x94, 0x64, 0x51, 0x71, 0xd5, 0xf4, 0x1e, 0xe2, 0xd2,
	0x9a, 0xef, 0xbd, 0xfc, 0xc1, 0x33, 0x0b, 0xdd, 0x4f, 0x47, 0x83, 0x3e, 0x43, 0xa8, 0x4d, 0x69,
	0xac, 0x66, 0xf3, 0x94, 0x64, 0xcb, 0xdd, 0x7a, 0x24, 0x75, 0x33, 0x7f, 0xb8, 0xbb, 0xa2, 0xcf,
	0x6c, 0xbe, 0x00, 0x3a, 0xf7, 0xdd, 0x56, 0xb5, 0x38, 0xfc, 0x73, 0x1f, 0x23, 0x61, 0x72, 0x9b,
	0xf0, 0xf4, 0xe8, 0x09, 0xde, 0xa5, 0x0b, 0x98, 0x8b, 0xf3, 0x45, 0x18, 0xe4, 0xab, 0xbb, 0x4e,
	0xf4, 0xbb, 0x5a, 0x91, 0x2a, 0x74, 0x8f, 0xbc, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x30, 0x8c,
	0xea, 0xec, 0xd4, 0x01, 0x00, 0x00,
}
