// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserStatus int32

const (
	UserStatus_invited UserStatus = 0
	UserStatus_created UserStatus = 1
	UserStatus_merged  UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "invited",
	1: "created",
	2: "merged",
}
var UserStatus_value = map[string]int32{
	"invited": 0,
	"created": 1,
	"merged":  2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}
func (UserStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type User struct {
	Id         string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email      string                      `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	CreatedAt  *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt  *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Verified   bool                        `protobuf:"varint,5,opt,name=verified" json:"verified,omitempty"`
	AuthToken  string                      `protobuf:"bytes,6,opt,name=authToken" json:"authToken,omitempty"`
	Status     UserStatus                  `protobuf:"varint,7,opt,name=status,enum=protobuf.UserStatus" json:"status,omitempty"`
	FacebookID string                      `protobuf:"bytes,8,opt,name=facebookID" json:"facebookID,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_invited
}

func (m *User) GetFacebookID() string {
	if m != nil {
		return m.FacebookID
	}
	return ""
}

type UserPublic struct {
	Id         string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email      string     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Status     UserStatus `protobuf:"varint,3,opt,name=status,enum=protobuf.UserStatus" json:"status,omitempty"`
	FacebookID string     `protobuf:"bytes,4,opt,name=facebookID" json:"facebookID,omitempty"`
}

func (m *UserPublic) Reset()                    { *m = UserPublic{} }
func (m *UserPublic) String() string            { return proto.CompactTextString(m) }
func (*UserPublic) ProtoMessage()               {}
func (*UserPublic) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *UserPublic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserPublic) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserPublic) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_invited
}

func (m *UserPublic) GetFacebookID() string {
	if m != nil {
		return m.FacebookID
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*UserPublic)(nil), "protobuf.UserPublic")
	proto.RegisterEnum("protobuf.UserStatus", UserStatus_name, UserStatus_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xb1, 0x6a, 0xf3, 0x30,
	0x14, 0x85, 0x7f, 0x39, 0x89, 0xe3, 0xdc, 0x40, 0x08, 0x22, 0x83, 0x08, 0x3f, 0xad, 0xc9, 0x64,
	0x4a, 0x71, 0x20, 0x5d, 0xba, 0x16, 0xba, 0x74, 0x2b, 0x6e, 0xfa, 0x00, 0x72, 0x74, 0xed, 0x8a,
	0xd8, 0x91, 0x91, 0xa5, 0xcc, 0x7d, 0x9c, 0x3e, 0x66, 0xb1, 0x6c, 0xc7, 0xa5, 0x4b, 0xdb, 0x49,
	0xdc, 0xa3, 0x73, 0x74, 0x3e, 0x5d, 0x00, 0x5b, 0xa3, 0x8e, 0x2b, 0xad, 0x8c, 0xa2, 0x81, 0x3b,
	0x52, 0x9b, 0xad, 0xaf, 0x73, 0xa5, 0xf2, 0x02, 0xb7, 0xbd, 0xb0, 0x35, 0xb2, 0xc4, 0xda, 0xf0,
	0xb2, 0x6a, 0xad, 0x9b, 0x0f, 0x0f, 0xc6, 0xaf, 0x35, 0x6a, 0xba, 0x00, 0x4f, 0x0a, 0x46, 0x42,
	0x12, 0xcd, 0x12, 0x4f, 0x0a, 0xba, 0x82, 0x09, 0x96, 0x5c, 0x16, 0xcc, 0x73, 0x52, 0x3b, 0xd0,
	0x7b, 0x98, 0x1d, 0x34, 0x72, 0x83, 0xe2, 0xc1, 0xb0, 0x51, 0x48, 0xa2, 0xf9, 0x6e, 0x1d, 0xb7,
	0x1d, 0x71, 0xdf, 0x11, 0xef, 0xfb, 0x8e, 0x64, 0x30, 0x37, 0x49, 0x5b, 0x89, 0x2e, 0x39, 0xfe,
	0x39, 0x79, 0x31, 0xd3, 0x35, 0x04, 0x67, 0xd4, 0x32, 0x93, 0x28, 0xd8, 0x24, 0x24, 0x51, 0x90,
	0x5c, 0x66, 0xfa, 0x1f, 0x66, 0xdc, 0x9a, 0xb7, 0xbd, 0x3a, 0xe2, 0x89, 0xf9, 0x8e, 0x74, 0x10,
	0xe8, 0x2d, 0xf8, 0xb5, 0xe1, 0xc6, 0xd6, 0x6c, 0x1a, 0x92, 0x68, 0xb1, 0x5b, 0x0d, 0x4d, 0xcd,
	0x9f, 0x5f, 0xdc, 0x5d, 0xd2, 0x79, 0xe8, 0x15, 0x40, 0xc6, 0x0f, 0x98, 0x2a, 0x75, 0x7c, 0x7a,
	0x64, 0x81, 0x7b, 0xec, 0x8b, 0xb2, 0x79, 0x27, 0x00, 0x4d, 0xec, 0xd9, 0xa6, 0x85, 0x3c, 0xfc,
	0x72, 0x61, 0x03, 0xc2, 0xe8, 0xcf, 0x08, 0xe3, 0xef, 0x08, 0x37, 0xbb, 0x96, 0xa0, 0x4d, 0xd1,
	0x39, 0x4c, 0xe5, 0xe9, 0x2c, 0x0d, 0x8a, 0xe5, 0xbf, 0x66, 0xe8, 0x96, 0xbd, 0x24, 0x14, 0xc0,
	0x2f, 0x51, 0xe7, 0x28, 0x96, 0x5e, 0xea, 0xbb, 0xc2, 0xbb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x88, 0x4f, 0x87, 0xec, 0x21, 0x02, 0x00, 0x00,
}
